### ISSUE TITLE
Cannot overwrite Input style

### ISSUE THREAD

**Issue by WeshGuillaume** [habx/thunder-ui#327]
``` javascript

const PartTitle = styled(TextInput)`
  font-weight: 400;
  font-size: 23px;
  line-height: 35px;
  margin-bottom: 16px;
`;

```

should overwrite the `font-weight`, `font-size`, `line-height` and `margin-bottom`

**Comment by flaviendelangle** [comment]
Currently the style and className are passed to the div container instead of the input itself
We could pass it to the input and add a containerClassName.

@jean9696

**Comment by jean9696** [comment]
I would rather have `inputClassName` for that. And @WeshGuillaume you can already style the `input` it self by doing 
```javascript
const PartTitle = styled(TextInput)`
 input {
    font-weight: 400;
    font-size: 23px;
     line-height: 35px;
     margin-bottom: 16px;
 }
`;
```
What do you think @flaviendelangle ?

**Comment by WeshGuillaume** [comment]
Oh yeah, that's a reasonable workaround
